name: siro_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal
  - rasterio
  - fiona
  - geopandas
  - shapely
  - pyproj
  - xarray
  - rioxarray
  - xarray-spatial
  - netcdf4
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - requests
  - tqdm
  - notebook
  - ipykernel
  - pip
  - pip:
      - metloom
